trigger:
  - staging
  - trying
  - main
jobs:
  - job: Markdownlint
    displayName: Markdownlint
    pool:
      vmImage: ubuntu-18.04
    steps:
      - script: sudo npm install -g markdownlint-cli
        displayName: Install markdownlint-cli
      - script: markdownlint '**/*.md'
        displayName: Run markdownlint
